repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
        files: FightPredix_scraping/*,FightPredixML/*
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
        files: FightPredix_scraping/*,FightPredixML/*
# -   repo: local
#     hooks:
#     -   id: run-pytest
#         name: Run pytest before push
#         entry: python -m pytest
#         language: system
#         pass_filenames: false
#         always_run: true
-   repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
    -   id: black
        files: FightPredix_scraping/*,FightPredixML/*
